"""Initial migration

Revision ID: 163eee16a658
Revises: de40b1e5db00
Create Date: 2024-06-06 16:12:58.643175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '163eee16a658'
down_revision = 'de40b1e5db00'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
