"""Initial migration

Revision ID: c3518c35fa74
Revises: 163eee16a658
Create Date: 2024-06-06 16:13:04.419480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3518c35fa74'
down_revision = '163eee16a658'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
